export const ADMIN_LOGIN_SUCCESS="ADMIN_LOGIN_SUCCESS"
export const ADMIN_LOGIN_FAIL="ADMIN_LOGIN_FAIL"
export const ADMIN_LOGOUT="ADMIN_LOGOUT"
export const CURRENT_ADMIN_USER="CURRENT_ADMIN_USER"

export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL="USER_LOGIN_FAIL"
export const USER_LOGOUT="USER_LOGOUT"
export const CURRENT_USER="CURRENT_USER"
